/* -------------------------------------------------------------------------------------------------------------------------------------- */
/* AUTO-GENERATED FILE. Source: BD.xlsx                                                                                                   */
/* Do not edit manually.                                                                                                                  */
/* -------------------------------------------------------------------------------------------------------------------------------------- */

#pragma once                                                                                                                                

#define LOCAL_PARAM_ID_BASE                0x8000u /** base offset for model-local ISIM identifiers                                       */
#define LCSPWR                             32768  /** CS: local model parameter                                                           */
#define LCSCLOCK                           32769  /** CS: local model parameter                                                           */
#define LCST                               32770  /** CS: local model parameter                                                           */
#define LMNSL1X                            32771  /** MNS: local model parameter                                                          */
#define LMNSL1Y                            32772  /** MNS: local model parameter                                                          */
#define LMNSL1Z                            32773  /** MNS: local model parameter                                                          */
#define LMNSL1ST                           32774  /** MNS: local model parameter                                                          */
#define LMNSL11X                           32775  /** MNS: local model parameter                                                          */
#define LMNSL11Y                           32776  /** MNS: local model parameter                                                          */
#define LMNSL11Z                           32777  /** MNS: local model parameter                                                          */
#define LMNSL11Q                           32778  /** MNS: local model parameter                                                          */
#define LMNSL11L                           32779  /** MNS: local model parameter                                                          */
#define LMNSL11A                           32780  /** MNS: local model parameter                                                          */
#define LMNSL12X                           32781  /** MNS: local model parameter                                                          */
#define LMNSL12Y                           32782  /** MNS: local model parameter                                                          */
#define LMNSL12Z                           32783  /** MNS: local model parameter                                                          */
#define LMNSL12Q                           32784  /** MNS: local model parameter                                                          */
#define LMNSL12L                           32785  /** MNS: local model parameter                                                          */
#define LMNSL12A                           32786  /** MNS: local model parameter                                                          */
#define LMNSL13X                           32787  /** MNS: local model parameter                                                          */
#define LMNSL13Y                           32788  /** MNS: local model parameter                                                          */
#define LMNSL13Z                           32789  /** MNS: local model parameter                                                          */
#define LMNSL13Q                           32790  /** MNS: local model parameter                                                          */
#define LMNSL13L                           32791  /** MNS: local model parameter                                                          */
#define LMNSL13A                           32792  /** MNS: local model parameter                                                          */
#define LMNSL2X                            32793  /** MNS: local model parameter                                                          */
#define LMNSL2Y                            32794  /** MNS: local model parameter                                                          */
#define LMNSL2Z                            32795  /** MNS: local model parameter                                                          */
#define LMNSL2ST                           32796  /** MNS: local model parameter                                                          */
#define LMNSL21X                           32797  /** MNS: local model parameter                                                          */
#define LMNSL21Y                           32798  /** MNS: local model parameter                                                          */
#define LMNSL21Z                           32799  /** MNS: local model parameter                                                          */
#define LMNSL21Q                           32800  /** MNS: local model parameter                                                          */
#define LMNSL21L                           32801  /** MNS: local model parameter                                                          */
#define LMNSL21A                           32802  /** MNS: local model parameter                                                          */
#define LMNSL22X                           32803  /** MNS: local model parameter                                                          */
#define LMNSL22Y                           32804  /** MNS: local model parameter                                                          */
#define LMNSL22Z                           32805  /** MNS: local model parameter                                                          */
#define LMNSL22Q                           32806  /** MNS: local model parameter                                                          */
#define LMNSL22L                           32807  /** MNS: local model parameter                                                          */
#define LMNSL22A                           32808  /** MNS: local model parameter                                                          */
#define LMNSL23X                           32809  /** MNS: local model parameter                                                          */
#define LMNSL23Y                           32810  /** MNS: local model parameter                                                          */
#define LMNSL23Z                           32811  /** MNS: local model parameter                                                          */
#define LMNSL23Q                           32812  /** MNS: local model parameter                                                          */
#define LMNSL23L                           32813  /** MNS: local model parameter                                                          */
#define LMNSL23A                           32814  /** MNS: local model parameter                                                          */
#define LMNSL3X                            32815  /** MNS: local model parameter                                                          */
#define LMNSL3Y                            32816  /** MNS: local model parameter                                                          */
#define LMNSL3Z                            32817  /** MNS: local model parameter                                                          */
#define LMNSL3ST                           32818  /** MNS: local model parameter                                                          */
#define LMNSL31X                           32819  /** MNS: local model parameter                                                          */
#define LMNSL31Y                           32820  /** MNS: local model parameter                                                          */
#define LMNSL31Z                           32821  /** MNS: local model parameter                                                          */
#define LMNSL31Q                           32822  /** MNS: local model parameter                                                          */
#define LMNSL31L                           32823  /** MNS: local model parameter                                                          */
#define LMNSL31A                           32824  /** MNS: local model parameter                                                          */
#define LMNSL32X                           32825  /** MNS: local model parameter                                                          */
#define LMNSL32Y                           32826  /** MNS: local model parameter                                                          */
#define LMNSL32Z                           32827  /** MNS: local model parameter                                                          */
#define LMNSL32Q                           32828  /** MNS: local model parameter                                                          */
#define LMNSL32L                           32829  /** MNS: local model parameter                                                          */
#define LMNSL32A                           32830  /** MNS: local model parameter                                                          */
#define LMNSL33X                           32831  /** MNS: local model parameter                                                          */
#define LMNSL33Y                           32832  /** MNS: local model parameter                                                          */
#define LMNSL33Z                           32833  /** MNS: local model parameter                                                          */
#define LMNSL33Q                           32834  /** MNS: local model parameter                                                          */
#define LMNSL33L                           32835  /** MNS: local model parameter                                                          */
#define LMNSL33A                           32836  /** MNS: local model parameter                                                          */
#define LMNSL4X                            32837  /** MNS: local model parameter                                                          */
#define LMNSL4Y                            32838  /** MNS: local model parameter                                                          */
#define LMNSL4Z                            32839  /** MNS: local model parameter                                                          */
#define LMNSL4ST                           32840  /** MNS: local model parameter                                                          */
#define LMNSL41X                           32841  /** MNS: local model parameter                                                          */
#define LMNSL41Y                           32842  /** MNS: local model parameter                                                          */
#define LMNSL41Z                           32843  /** MNS: local model parameter                                                          */
#define LMNSL41Q                           32844  /** MNS: local model parameter                                                          */
#define LMNSL41L                           32845  /** MNS: local model parameter                                                          */
#define LMNSL41A                           32846  /** MNS: local model parameter                                                          */
#define LMNSL42X                           32847  /** MNS: local model parameter                                                          */
#define LMNSL42Y                           32848  /** MNS: local model parameter                                                          */
#define LMNSL42Z                           32849  /** MNS: local model parameter                                                          */
#define LMNSL42Q                           32850  /** MNS: local model parameter                                                          */
#define LMNSL42L                           32851  /** MNS: local model parameter                                                          */
#define LMNSL42A                           32852  /** MNS: local model parameter                                                          */
#define LMNSL43X                           32853  /** MNS: local model parameter                                                          */
#define LMNSL43Y                           32854  /** MNS: local model parameter                                                          */
#define LMNSL43Z                           32855  /** MNS: local model parameter                                                          */
#define LMNSL43Q                           32856  /** MNS: local model parameter                                                          */
#define LMNSL43L                           32857  /** MNS: local model parameter                                                          */
#define LMNSL43A                           32858  /** MNS: local model parameter                                                          */
#define LMNSR1X                            32859  /** MNS: local model parameter                                                          */
#define LMNSR1Y                            32860  /** MNS: local model parameter                                                          */
#define LMNSR1Z                            32861  /** MNS: local model parameter                                                          */
#define LMNSR1ST                           32862  /** MNS: local model parameter                                                          */
#define LMNSR11X                           32863  /** MNS: local model parameter                                                          */
#define LMNSR11Y                           32864  /** MNS: local model parameter                                                          */
#define LMNSR11Z                           32865  /** MNS: local model parameter                                                          */
#define LMNSR11Q                           32866  /** MNS: local model parameter                                                          */
#define LMNSR11L                           32867  /** MNS: local model parameter                                                          */
#define LMNSR11A                           32868  /** MNS: local model parameter                                                          */
#define LMNSR12X                           32869  /** MNS: local model parameter                                                          */
#define LMNSR12Y                           32870  /** MNS: local model parameter                                                          */
#define LMNSR12Z                           32871  /** MNS: local model parameter                                                          */
#define LMNSR12Q                           32872  /** MNS: local model parameter                                                          */
#define LMNSR12L                           32873  /** MNS: local model parameter                                                          */
#define LMNSR12A                           32874  /** MNS: local model parameter                                                          */
#define LMNSR13X                           32875  /** MNS: local model parameter                                                          */
#define LMNSR13Y                           32876  /** MNS: local model parameter                                                          */
#define LMNSR13Z                           32877  /** MNS: local model parameter                                                          */
#define LMNSR13Q                           32878  /** MNS: local model parameter                                                          */
#define LMNSR13L                           32879  /** MNS: local model parameter                                                          */
#define LMNSR13A                           32880  /** MNS: local model parameter                                                          */
#define LMNSR2X                            32881  /** MNS: local model parameter                                                          */
#define LMNSR2Y                            32882  /** MNS: local model parameter                                                          */
#define LMNSR2Z                            32883  /** MNS: local model parameter                                                          */
#define LMNSR2ST                           32884  /** MNS: local model parameter                                                          */
#define LMNSR21X                           32885  /** MNS: local model parameter                                                          */
#define LMNSR21Y                           32886  /** MNS: local model parameter                                                          */
#define LMNSR21Z                           32887  /** MNS: local model parameter                                                          */
#define LMNSR21Q                           32888  /** MNS: local model parameter                                                          */
#define LMNSR21L                           32889  /** MNS: local model parameter                                                          */
#define LMNSR21A                           32890  /** MNS: local model parameter                                                          */
#define LMNSR22X                           32891  /** MNS: local model parameter                                                          */
#define LMNSR22Y                           32892  /** MNS: local model parameter                                                          */
#define LMNSR22Z                           32893  /** MNS: local model parameter                                                          */
#define LMNSR22Q                           32894  /** MNS: local model parameter                                                          */
#define LMNSR22L                           32895  /** MNS: local model parameter                                                          */
#define LMNSR22A                           32896  /** MNS: local model parameter                                                          */
#define LMNSR23X                           32897  /** MNS: local model parameter                                                          */
#define LMNSR23Y                           32898  /** MNS: local model parameter                                                          */
#define LMNSR23Z                           32899  /** MNS: local model parameter                                                          */
#define LMNSR23Q                           32900  /** MNS: local model parameter                                                          */
#define LMNSR23L                           32901  /** MNS: local model parameter                                                          */
#define LMNSR23A                           32902  /** MNS: local model parameter                                                          */
#define LMNSR3X                            32903  /** MNS: local model parameter                                                          */
#define LMNSR3Y                            32904  /** MNS: local model parameter                                                          */
#define LMNSR3Z                            32905  /** MNS: local model parameter                                                          */
#define LMNSR3ST                           32906  /** MNS: local model parameter                                                          */
#define LMNSR31X                           32907  /** MNS: local model parameter                                                          */
#define LMNSR31Y                           32908  /** MNS: local model parameter                                                          */
#define LMNSR31Z                           32909  /** MNS: local model parameter                                                          */
#define LMNSR31Q                           32910  /** MNS: local model parameter                                                          */
#define LMNSR31L                           32911  /** MNS: local model parameter                                                          */
#define LMNSR31A                           32912  /** MNS: local model parameter                                                          */
#define LMNSR32X                           32913  /** MNS: local model parameter                                                          */
#define LMNSR32Y                           32914  /** MNS: local model parameter                                                          */
#define LMNSR32Z                           32915  /** MNS: local model parameter                                                          */
#define LMNSR32Q                           32916  /** MNS: local model parameter                                                          */
#define LMNSR32L                           32917  /** MNS: local model parameter                                                          */
#define LMNSR32A                           32918  /** MNS: local model parameter                                                          */
#define LMNSR33X                           32919  /** MNS: local model parameter                                                          */
#define LMNSR33Y                           32920  /** MNS: local model parameter                                                          */
#define LMNSR33Z                           32921  /** MNS: local model parameter                                                          */
#define LMNSR33Q                           32922  /** MNS: local model parameter                                                          */
#define LMNSR33L                           32923  /** MNS: local model parameter                                                          */
#define LMNSR33A                           32924  /** MNS: local model parameter                                                          */
#define LMNSR4X                            32925  /** MNS: local model parameter                                                          */
#define LMNSR4Y                            32926  /** MNS: local model parameter                                                          */
#define LMNSR4Z                            32927  /** MNS: local model parameter                                                          */
#define LMNSR4ST                           32928  /** MNS: local model parameter                                                          */
#define LMNSR41X                           32929  /** MNS: local model parameter                                                          */
#define LMNSR41Y                           32930  /** MNS: local model parameter                                                          */
#define LMNSR41Z                           32931  /** MNS: local model parameter                                                          */
#define LMNSR41Q                           32932  /** MNS: local model parameter                                                          */
#define LMNSR41L                           32933  /** MNS: local model parameter                                                          */
#define LMNSR41A                           32934  /** MNS: local model parameter                                                          */
#define LMNSR42X                           32935  /** MNS: local model parameter                                                          */
#define LMNSR42Y                           32936  /** MNS: local model parameter                                                          */
#define LMNSR42Z                           32937  /** MNS: local model parameter                                                          */
#define LMNSR42Q                           32938  /** MNS: local model parameter                                                          */
#define LMNSR42L                           32939  /** MNS: local model parameter                                                          */
#define LMNSR42A                           32940  /** MNS: local model parameter                                                          */
#define LMNSR43X                           32941  /** MNS: local model parameter                                                          */
#define LMNSR43Y                           32942  /** MNS: local model parameter                                                          */
#define LMNSR43Z                           32943  /** MNS: local model parameter                                                          */
#define LMNSR43Q                           32944  /** MNS: local model parameter                                                          */
#define LMNSR43L                           32945  /** MNS: local model parameter                                                          */
#define LMNSR43A                           32946  /** MNS: local model parameter                                                          */

#define LOCAL_PARAM_max                    179    /**                                                                                     */
